name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{tsx,js,ts,md,css,scss,html,json,yml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    name: ESLint
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Node.js dependencies
        run: npm install

      - name: Run ESLint
        working-directory: ./src/
        run: npx eslint **/*.{tsx,js,ts} --no-error-on-unmatched-pattern

  build-and-test:
    name: Build and Test
    needs: [prettier, eslint]
    runs-on: ubuntu-latest
    steps:
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: |
          # npm i react-scripts@latest
          # npm install @capacitor/core@latest @capacitor/cli@latest
          npm install -force

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
